image: docker:latest
services:
  - docker:dind

cache:
  paths:
   - .m2/repository

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - test
  - build
  - package
  - deploy

# maven-test:
#   image: maven:3-jdk-11
#   stage: test
#   script:
#     - mvn verify --file tracking-server/pom.xml
#   artifacts:
#     reports:
#       junit:
#         - tracking-server/surefire-reports/TEST-*.xml
#         - tracking-server/failsafe-reports/TEST-*.xml
#   rules:
#     - if: $CI_COMMIT_TAG
#     - if: '$CI_PIPELINE_SOURCE == "web"'
#     - if: '$CI_PIPELINE_SOURCE == "chat"'
#   tags:
#     - arvan

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: 
   - mvn package -B -Dmaven.test.skip=true --file tracking-server/pom.xml
   - ls -R
  artifacts:
    paths:
      - tracking-server/*.jar
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'
  tags:
    - arvan

docker-build:
  stage: package
  script:
   - docker build -t registry.gitlab.com/toofun-group/kaseb-tracking-server .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
   - docker push registry.gitlab.com/toofun-group/kaseb-tracking-server
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

nl-deploy:
  stage: deploy
  script:
    - whoami
    - sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - sudo docker-compose -f /docker-compose.yml pull tracking-server
    - sudo docker-compose -f /docker-compose.yml up -d
#  - echo -e "$ARVAN_CLI_TOKEN\n"
#  - echo -e "$ARVAN_CLI_TOKEN\n" | arvan login
#  - arvan paas status
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'
  tags:
    - nl1
