version: "3"

services:

  #  ----------------
  #  Infrastructure
  #  ----------------

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "4369:4369"
      - "5671:5671" # used by AMQP 0-9-1 and 1.0 clients without and with TLS
      - "5672:5672" # used by AMQP 0-9-1 and 1.0 clients without and with TLS
      - "15671:15671" # management ssl port
      - "15672:15672" # management tcp port
      - "25672:25672" # used for inter-node and CLI tools communication
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - kaseb-network
  #  ----------------
  #  Services
  #  ----------------

networks:
  kaseb-network: