spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          max-attempts: 3
  application:
    name: tracking-service
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 1313

tracking-service:
  exchange:
    name: "tracking-exchange"
  queue:
    name: "tracking-queue"
  routing:
    key: "tracking"
monitoring:
  user: kaseb
  password: HW9Z954sefKxpWDDtcxEaZF2MEtQAccBW2Sb4B4ng22JThDUs9rSDccyRXP3

services:
  infrastructure:
    harness:
      base-url: "https://harness.kaseb.xyz"
      username: "kaseb"
      password: "sWn9nS0hXS1pcnGvkryh"